import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import { GlobalStyle } from "../components/component1";
import React from 'react';
import { ThemeProvider } from 'styled-components';


const themes = [
  {
    backgroundColor: '#FFC7DF',
    textColor: 'black',
  },
  {
    backgroundColor: '#FFFDE7',
    textColor: 'black',
  },
  {
    backgroundColor: '#FFEFE7',
    textColor: 'black',
  },
  {
    backgroundColor: '#7C5767',
    textColor: 'black',
  },
  {
    backgroundColor: '#FFFDF8',
    textColor: 'black',
  },
  {
    backgroundColor: '#FFAB89',
    textColor: 'black',
  },
  {
    backgroundColor: '#F9FCFF',
    textColor: 'black',
  },
  // Add more themes as needed
];
function getRandomTheme() {
  return themes[Math.floor(Math.random() * themes.length)];
}

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const theme = getRandomTheme();
  return (
    // <React.StrictMode>
    <ThemeProvider theme={theme}>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      < main>
        <div >
        <GlobalStyle/>
          <h1 style={{fontSize: 50}}> 
            This is backgroundcolor change of alans project
         </h1>
          </div>     
      </main>
    </>
     </ThemeProvider>
    //  </React.StrictMode>
  );
}
